variables:
  DOCKER_BUILDKIT: 1
  APP_NAME: 'upod-FE'
  PORT: '5173'

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker stop $APP_NAME || true
    - docker rm $APP_NAME || true
    - docker system prune -f || true
    - docker pull $CI_REGISTRY_IMAGE
    - docker container run -d --restart unless-stopped --name $APP_NAME -p $PORT:5173 $CI_REGISTRY_IMAGE
    - docker logout
  tags:
    - shell
